<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BookyServer.Infrastructure\BookyServer.Infrastructure.csproj" />
    <ProjectReference Include="..\BookyServer.Interfaces\BookyServer.Interfaces.csproj" />
    <ProjectReference Include="..\BookyServer.Application\BookyServer.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Middlewares\" />
  </ItemGroup>
</Project>
